import { Status } from "./permission.enum";

export enum AUTH_PERMISSIONS {
  ROLE_CREATE = "ROLE_CREATE",
  ROLE_UPDATE = "ROLE_UPDATE",
  ROLE_VIEW = "ROLE_VIEW",
  ROLE_DELETE = "ROLE_DELETE",

  HOTEL_CREATE = "HOTEL_CREATE",
  HOTEL_UPDATE = "HOTEL_UPDATE",
  HOTEL_VIEW = "HOTEL_VIEW",
  HOTEL_DELETE = "HOTEL_DELETE",

  PERMISSION_UPDATE = "PERMISSION_UPDATE",
  PERMISSION_VIEW = "PERMISSION_VIEW",
  PERMISSION_DELETE = "PERMISSION_DELETE",
  TOUR_CREATE = "TOUR_CREATE",
  TOUR_UPDATE = "TOUR_CREATE",
  TOUR_VIEW = "TOUR_VIEW",
  TOUR_DELETE = "TOUR_DELETE",
  CUSTOMER_CREATE = "CUSTOMER_CREATE",
  CUSTOMER_UPDATE = "CUSTOMER_UPDATE",
  CUSTOMER_VIEW = "CUSTOMER_VIEW",
  CUSTOMER_DELETE = "CUSTOMER_DELETE",
  USER_VIEW = "USER_VIEW",
}

export enum USER_PERMISSIONS {
  HOTEL_VIEW = AUTH_PERMISSIONS.HOTEL_VIEW,
}

export const AUTH_ROLES = {
  ROLE: {
    ROLE_CREATE: Status.PUBLISHED,
    ROLE_UPDATE: Status.PUBLISHED,
    ROLE_VIEW: Status.PUBLISHED,
    ROLE_DELETE: Status.PUBLISHED,
  },
  HOTEL: {
    HOTEL_CREATE: Status.PUBLISHED,
    HOTEL_UPDATE: Status.PUBLISHED,
    HOTEL_VIEW: Status.PUBLISHED,
    HOTEL_DELETE: Status.PUBLISHED,
  },
  PERMISSION: {
    PERMISSION_UPDATE: Status.PUBLISHED,
    PERMISSION_VIEW: Status.PUBLISHED,
    PERMISSION_DELETE: Status.PUBLISHED,
  },
  TOUR: {
    TOUR_CREATE: Status.PUBLISHED,
    TOUR_UPDATE: Status.PUBLISHED,
    TOUR_VIEW: Status.PUBLISHED,
    TOUR_DELETE: Status.PUBLISHED,
  },
  CUSTOMER: {
    CUSTOMER_CREATE: Status.PUBLISHED,
    CUSTOMER_UPDATE: Status.PUBLISHED,
    CUSTOMER_VIEW: Status.PUBLISHED,
    CUSTOMER_DELETE: Status.PUBLISHED,
  },
  USER: {
    USER_VIEW: Status.PUBLISHED,
  },
};

export const AUTH_PERMISSION_META_KEY = "auth_permission_meta_key";
